services:  
  application:
    image: node:lts-alpine
    container_name: "grubhunter-application"
    ports:
      - "3000:3000"
    volumes:
      - "./code:/home/node/code"
    working_dir: "/home/node/code/grub-hunter"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - backend
    tty: true
    command: "npm run dev"
  
  backend:
    image: mongo:latest
    container_name: "grubhunter-backend"
    restart: always
    environment:
      - DB_NAME="grubhunter-db"
      - MONGO_INITDB_DATABASE="grubhunter-db"
    ports:
      - "27017:27017"
    volumes:
      - "./.docker/grubhunter-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js"
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: