import Head from "next/head";
import { LocationList } from "@/components/locations-list";
import { InferGetStaticPropsType, GetStaticProps, GetStaticPropsContext } from "next";
import { findAllLocations } from "@/mongoose/locations/services";
import { LocationType } from "@/mongoose/locations/schema";
import mongoConnect from "@/middleware/mongo-connect";

export default function Home(props: InferGetStaticPropsType<typeof getStaticProps>) {
  const title = "GrubHunter Application";
  let locations : LocationType[] = JSON.parse(props.loc_json);
  
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      <div>
        <main>
          <LocationList location_items={locations}></LocationList>
        </main>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
  let locations: Array<LocationType | undefined> = [];
  let loc_json : String = "";
  try {
    await mongoConnect();
    locations = await findAllLocations();
    loc_json = JSON.stringify(locations);
  } catch (err) { console.log(err) }

  return {
    props: {
      loc_json
    }
  }
}